postgres:
  outputs:
    dev:
      dbname: weather_db
      host: localhost
      pass: sunnycloudy
      port: 5432
      schema: public
      threads: 5
      type: postgres
      user: root
  target: dev
