postgres:
  outputs:
    dev:
      dbname: {{ env_var('POSTGRES_DATABASE') }}
      host: {{ env_var('POSTGRES_HOST') }}
      pass: {{ env_var('POSTGRES_PASSWORD') }}
      port: {{ env_var('POSTGRES_PORT') }}
      schema: public
      threads: 5
      type: postgres
      user: root
  target: dev
