version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: weather_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sunnycloudy
    ports:
      - "5432:5432"

volumes:
  db-data:
